requirejs.config({
    baseUrl: '../src/js/frontend/',
    paths: {
        // libraries
        jQuery: 'libs/jquery.min',
        sortable: 'libs/sortable.min',
        mask: 'libs/jquery.mask.min',
        angular: 'libs/angular.min',
        ace: 'libs/ace/ace',
        aws: 'libs/aws-sdk.min',
        bootstrap: 'libs/bootstrap.min',
        charts: 'libs/charts.min',
        cropper: 'libs/cropper.min',
        localforage: 'libs/localforage',
        geocomplete: 'libs/geocomplete',
        moment: 'libs/moment.min',
        datetimepicker: 'libs/datetimepicker',
        messenger: 'libs/messenger',
        intro: 'libs/intro',
        qstn: 'libs/qstn',
        owl: 'libs/owl',
        particle: 'libs/particle',
        progress: 'libs/progressbar.min',
        jSignature: 'libs/jsignature.min',
        sign: 'controller/core/signature',
        searcher: 'libs/searcher',
        youtube: 'libs/youtube',
        typewriter: 'libs/typewriter',
        calendar: 'libs/fullcalendar.min',
        // cryptoJS
        AES: 'libs/cryptoJS/aes',
        MD5: 'libs/cryptoJS/md5',
        // controller
        app: 'controller/app',
        // core
        api: 'controller/core/api',
        buildr: 'controller/core/buildr',
        config: 'controller/core/config',
        editor: 'controller/core/editor',
        error: 'controller/core/error',
        page: 'controller/core/page',
        user: 'controller/core/user',
        // default
        main: 'main',
        // pages
        about: 'controller/pages/about',
        appointment: 'controller/pages/appointment',
        blog: 'controller/pages/blog',
        contact: 'controller/pages/contact',
        dashboard: 'controller/pages/dashboard',
        form: 'controller/pages/form',
        home: 'controller/pages/home',
        insurance: 'controller/pages/insurance',
        services: 'controller/pages/services',
        medicalpractice: 'controller/pages/medical-practice',
        aestheticpractice: 'controller/pages/aesthetic-practice',
        patient: 'controller/pages/patient-registration',
        patientInfo: 'controller/pages/patient-info',
        medicalRecords: 'controller/pages/medical-records-request'
    },
    shim: {
        'bootstrap': ['jQuery'],
        'sortable': ['jQuery'],
        'mask': ['jQuery'],
        'geocomplete': ['jQuery'],
        'jSignature': ['jQuery'],
        'fullcalendar': ['jQuery','moment']
    }
});